#  _   _       ______    _ _
# | \ | |     |  ____|  | | |
# |  \| | ___ | |__ __ _| | |
# | . ` |/ _ \|  __/ _` | | |
# | |\  | (_) | | | (_| | | |
# |_| \_|\___/|_|  \__,_|_|_|

name: NoFall
description: A plugin that disables fall damage using PocketMine API
author: Diduhless
website: https://twitter.com/Diduhless
main: Diduhless\NoFall\NoFall
version: "1.0.0"
api: 3.0.0